config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get  '/share', to: 'sharing#new'
  post '/share', to: 'sharing#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/medium.rb
# == Schema Information
#
# Table name: media
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  url         :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_media_on_url_and_user_id  (url,user_id) UNIQUE
#  index_media_on_user_id          (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Medium < ApplicationRecord
  belongs_to :user

  validates_uniqueness_of :url, scope: :user_id

  paginates_per 5
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login],
         reset_password_keys: [:login]

  attr_writer :login

  validates :email, format: {
    with: URI::MailTo::EMAIL_REGEXP,
    message: 'must be a valid email address',
  }
  validates :username, uniqueness: true

  has_many :media, dependent: :destroy

  def login
    @login || username || email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h)
        .where(['username = :value OR lower(email) = lower(:value)', { value: login }])
        .first
    elsif conditions.key?(:username) || conditions.key?(:email)
      conditions[:email]&.downcase!
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :config_devise_params, if: :devise_controller?

  protected

  def config_devise_params
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: %i[
        username
        email
        password
        password_confirmation
      ],
    )

    devise_parameter_sanitizer.permit :sign_in, keys: %i[login password]
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home page
class HomeController < ApplicationController
  def index
    @media = Kaminari.paginate_array(Medium.all.reverse).page(params[:page]).per(5)
  end
end

app/controllers/sharing_controller.rb
# frozen_string_literal: true

# This controller manage the sharing of user about youtube url
class SharingController < ApplicationController
  before_action :authenticate_user!

  def new
    @medium = Medium.new
  end

  # rubocop:disable Metrics/MethodLength
  def create
    @medium = Medium.new(medium_params)
    @medium.user = current_user

    url = @medium.url
    yt_info_url = "https://www.youtube.com/oembed?url=#{url}&format=json"

    title = get_youtube_video_info(yt_info_url)

    if title.nil?
      @medium.errors.add(:base, 'Can not retrieve data from Youtube.Please try another way')
    else
      @medium.title = title
      redirect_to root_path and return if @medium.save
    end

    render :new, status: :unprocessable_entity
  end
  # rubocop:enable Metrics/MethodLength

  private

  def medium_params
    params.require(:medium).permit(:url, :description)
  end

  def get_youtube_video_info(url)
    begin
      response = Faraday.get(url)
      youtube_info = JSON.parse(response.body)
    rescue StandardError
      return nil
    end

    return nil if youtube_info.nil?

    youtube_info['title']
  end
end

app/controllers/turbo_devise_controller.rb
# frozen_string_literal: true

class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  TRUNCATE_SIZE = 100

  def truncate_youtube_id(youtube_url)
    youtube_url.split('=').last
  end

  def make_youtube_embed_url(youtube_url)
    "https://www.youtube.com/embed/#{truncate_youtube_id(youtube_url)}?rel=0&autoplay=0"
  end

  def truncate_description(description)
    description.truncate(TRUNCATE_SIZE)
  end
end

app/helpers/sharing_helper.rb
module SharingHelper
end

app/views/home/index.html.erb
<%= render 'layouts/header' %>
<div class="home">
  <div class="video-part">
    <% @media.each do |medium| %>
      <div class="line">
        <div class="video-content">
          <iframe src='<%= make_youtube_embed_url(medium.url) %>' frameborder='0' allowfullscreen></iframe>
        </div>
        <div class="video-info">
          <div class="title">
            <%= medium.title %>
          </div>
          <div class="author">
            Share by <%= medium.user.username %>
          </div>
          <div class="description">
            <div data-controller="readmore"
                data-readmore-full-content-value="<%= medium.description %>"
                data-readmore-hide-class="hide"
              >
              <div data-readmore-target="content">
                <%= truncate_description(medium.description) %>
              </div>
              <button 
                class="hide btn-showMore"
                data-readmore-target="moreButton"
                data-action="readmore#showMore"
              >
                Show more
              </button>
              <button 
                class="hide btn-showMore"
                data-readmore-target="lessButton"
                data-action="readmore#showLess"
              >
                Show less
              </button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @media %>
</div>

app/views/layouts/_head.html.erb
<head>
  <title>Buggy</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <%= csrf_meta_tags %> 
  <%= csp_meta_tag %> 
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

app/views/layouts/_header.html.erb
<nav class="navbar">
  <div class="content">
    <div class="name">
      <%= link_to root_path do %>
        <h1>Funny Movies</h1>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="btn-group">
        <%= button_to share_path, method: :get, class: "btn" do %>
          Share
        <% end %>
        <%= button_to destroy_user_session_path, class: "btn", method: :delete do %>
          Log out
        <% end %>
      </div>
    <% else %>
      <div class="">
        <%= button_to new_user_session_path, class: "btn" do %>
          Login
        <% end %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body>
    <main class="">
      <%= yield %>
    </main>
  </body>
</html>

app/views/sharing/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Sharing#create</h1>
  <p>Find me in app/views/sharing/create.html.erb</p>
</div>

app/views/sharing/new.html.erb
<%= render 'layouts/header' %>
<div class="sharing">
  <div class="sharing-form">
    <% if @medium.errors.any? %>
      <ul>
        <% @medium.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="sharing-form-content">
      <%= form_with model: @medium, url: share_path do |f| %>
        <div class="text-field">
          <%= f.label :url, "Youtube URL" %>
          <%= f.text_field :url, autofocus: true %>
        </div>
        <div class="text-field">
          <%= f.label :description %>
          <%= f.text_area :description, placeholder: "Share your thought right now ;)", rows: "5" %>
        </div>
        <div class="sharing-form-footer">
          <%= f.submit "Share", class: "btn-sharing" %>
        </div>
      <% end %>
    </div>
  </div>
</div>